--- 
abstract: YAML Data Serialization for JavaScript
author: "Ingy d\xC3\xB6t Net <ingy@cpan.org>"
distribution_type: module
generated_by: Module::Install version 0.67
license: lgpl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: JS-YAML
no_index: 
  directory: 
    - inc
    - t
version: 0.11
